### ISSUE TITLE
Publish JavaScript sample app to GitHub pages

### ISSUE THREAD

**Issue by twyatt** [JuulLabs/krayon#28]
After #8 is merged, can look into getting the sample app published alongside the Dokka documentation.

**Comment by cedrickcooke** [comment]
We might have to make the sample app something impressive if we do this. 😂

**Comment by twyatt** [comment]
> We might have to make the sample app something impressive if we do this. 😂

Great products ship!

I'll do it even if it's still "ugly". 😝 
Maybe it will motivate us to improve the sample app, if not, it is still better than nothing.

**Comment by twyatt** [comment]
@cedrickcooke which [theme](https://pages.github.com/themes/) do you want?

1. [architect](https://pages-themes.github.io/architect/)
2. [Cayman](https://pages-themes.github.io/cayman/)
3. [Dinky](https://pages-themes.github.io/dinky/)
4. [Hacker](https://pages-themes.github.io/hacker/)
5. [Leap day](https://pages-themes.github.io/leap-day/)
6. [Merlot](https://pages-themes.github.io/merlot/)
7. [Midnight](https://pages-themes.github.io/midnight/)
8. [minima](https://jekyll.github.io/minima/)
9. [Minimal](https://pages-themes.github.io/minimal/)
10. [Modernist](https://pages-themes.github.io/modernist/)
11. [Slate](https://pages-themes.github.io/slate/)
12. [Tactile](https://pages-themes.github.io/tactile/)
13. [Time machine](https://pages-themes.github.io/time-machine/)

**Comment by cedrickcooke** [comment]
Mega late seeing this. Cayman and Slate both seem good.
